consumption/urls.py
'''
Created on Nov 2, 2013

@author: shengeng
'''
from django.conf.urls import patterns, url

from consumption import views

urlpatterns = patterns('',
    url(r'^webview/([0-9]*)/$', views.consumption_web_view),
    url(r'^addconsumption/', views.consumptionFormView.as_view(success_url='/consumption/addconsumption/')),
    url(r'^addconsumptioncomment/(\d+)/$', views.addconsumptioncomment),
)

shop/urls.py
'''
Created on Nov 2, 2013

@author: shengeng
'''
from django.conf.urls import patterns, url

from shop import views

urlpatterns = patterns('',
    url(r'^webview/([0-9]*)/$', views.web_view),
    url(r'^addshop/', views.ShopFormView.as_view(success_url='/shop/addshop/')),
    url(r'^addshopcomment/(\d+)/$', views.addshopcomment),
)

ywbserver/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ywbserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^knowledge/', include('knowledge.urls')),
    url(r'^shop/', include('shop.urls')),
    url(r'^consumption/', include('consumption.urls')),
    url(r'^mobile/', include('mobile.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^weather/', include('weather.urls')),
    url(r'^weixin/', include('weixin.urls')),
)

consumption/models.py
from django.db import models
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, fromstr
from django.contrib.gis.measure import D # alias for Distance
import random
# Create your models here.

class Consumption(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    abstract = models.CharField(max_length=1000)
    description = models.CharField(max_length=5000)
    url = models.CharField(max_length=1000)
    begin = models.DateTimeField()
    end = models.DateTimeField()
    point = models.PointField()
    objects = models.GeoManager()

class EduConsumption(models.Model):
    pass

class EntertainConsumption(models.Model):
    pass

class ConsumptionComment(models.Model):
    consumptionid = models.ForeignKey(Consumption)
    comment = models.CharField(max_length=500)


def get_consumption_nearby(latitude, longitude, number=1, distance = 5000):
    point = fromstr("POINT(%s %s)" % (longitude, latitude))
    nearby = Consumption.objects.filter(point__distance_lt=(point, D(km=int(distance)/1000)))
    count = nearby.count()
    if number >= count:
        print('consumption nearby %f,%f is not enough' % (latitude, longitude))
        return list(Consumption.objects.all()[:number])
    else:
        return random.sample(list(nearby), number)

def get_consumption_random(number=1):
    all = Consumption.objects.all()
    count = all.count()
    if number >= count:
        print('consumption random  is not enough')
        return list(all[:count])
    else:
        return random.sample(list(all), number)

consumption/forms.py
'''
Created on 2013年12月31日

@author: shengeng
'''

from django import forms
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User 

class consumptionForm(forms.Form):
    name = forms.CharField()
    city = forms.CharField()
    address = forms.CharField()
    description = forms.CharField()
    url = forms.CharField()


    

consumption/views.py
from django.shortcuts import render
from django.http import *
from django.utils import http
from datetime import *
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import get_template
from django.template import Context
from django.views.generic import FormView, TemplateView
from django.contrib.gis.geos import Point, fromstr
from django.contrib.gis.measure import D # alias for Distance
from django.utils.safestring import SafeString

from .models import *
from .forms import *
from weixin.baidumap import *
import hashlib, time, random
# Create your views here.

def consumption_web_view(request, oid):
    try:
        oid = int(oid)
        o = Consumption.objects.get(id = oid)
        t = get_template('consumption/consumption.html')
        c = {}
        c['consumption_consumptionid'] = o.id
        c['consumption_title'] = o.name
        c['consumption_content'] = o.description
        c['consumption_address'] = o.address
        c['consumption_url'] = o.url
        picindex = random.randint(0,9)
        c['pic'] = 'http://wjbb.cloudapp.net:8001/pic/'+str(picindex)+'.jpg'
        c['comments'] = ConsumptionComment.objects.filter(consumptionid=o)
        html = t.render(Context(c))
        return HttpResponse(html)
    except ValueError:
        raise Http404()

@csrf_exempt
def addconsumptioncomment(request, consumptionid):
    consumption = Consumption.objects.get(id=int(consumptionid))
    consumptioncomment = ConsumptionComment(consumptionid=consumption, comment=request.POST['consumptioncomment'])
    consumptioncomment.save()
    return consumption_web_view(request, consumptionid)
    
class consumptionFormView(FormView):
    template_name = 'consumption/consumptionform.html'
    form_class = consumptionForm
    def get_context_data(self, **kwargs):
        context = super(consumptionFormView, self).get_context_data(**kwargs)
        return context
    
    def form_valid(self, form):
        address = form.cleaned_data['address']
        baidu_resp = get_baidu_location(address)
        if not baidu_resp['result']:
            baidu_resp = get_baidu_location('百度大厦')
            address = '百度大厦'
        longitude = baidu_resp['result']['location']['lng']
        latitude = baidu_resp['result']['location']['lat']
        point = fromstr("POINT(%s %s)" % (longitude, latitude))
        consumption = Consumption()
        consumption.name = form.cleaned_data['name']
        consumption.city = form.cleaned_data['city']
        consumption.address = form.cleaned_data['address']
        consumption.url = form.cleaned_data['url']
        consumption.description = form.cleaned_data['description']
        consumption.point = point
        consumption.begin = datetime.now()
        consumption.end = datetime.now()
        consumption.save()
        return super(consumptionFormView, self).form_valid(form)

templates/consumption/consumption.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1" />
</head>
<body>
<div align="center">
<img src={{pic}}  style="width: 300px; height: 241px, display:inline">
</div>
<span align="center">
<h2>
{{consumption_title}}<br/>
</h2>
</span>

<span>
<h3>
消费地址：{{consumption_address}}
</h3>
</span>

<span>
<h3>
消费简介：{{consumption_content}}
</h3>
<br/></span>

<span>
<h3>
<a href="{{consumption_url}}">链接</a>
</h3>
</span>
<br></br>
<label>写评论</label>

<form action="{% url 'consumption.views.addconsumptioncomment' consumption_consumptionid %}" method="post">
<textarea name="consumptioncomment" cols="40" rows="3"></textarea>
<input type="submit" value="发布" />
<br></br>
<label>评论</label>
<ul>
{% for comment in comments %}
<li>{{comment.comment}}</li>
{% endfor %}
</ul>
</form>

</body>
</html>

templates/consumption/consumptionform.html
<html>
<head>
    <title>Forms</title>
</head>
<body>
    <h1>add consumption</h1>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}
    <form name="consumptionform" action="" method="post" >
    {% csrf_token %}
        <div class="field">
            {{ form.name.errors }}
            <label for="id_name">name:</label>
            {{ form.name }}
        </div>
       <div class="field">
            {{ form.city.errors }}
            <label for="id_city">city:</label>
            {{ form.city }}
        </div>
        <div class="field">
            {{ form.address.errors }}
            <label for="id_address">address:</label>
            {{ form.address }}
        </div>
        <div class="field">
            {{ form.url.errors }}
            <label for="id_url">url:</label>
            {{ form.url }}
        </div>
        <div class="field">
            {{ form.description.errors }}
            <label for="id_description">description:</label>
            {{ form.description }}
        </div>
        <input type="submit" value="Add consumption"/>
    </form>
</body>

</html>